DogDC/Models/Pet.cs
using System;
using System.Collections.Generic;

namespace DogDC.Models
{
    public partial class Pet
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int Age { get; set; }
        public string Diet { get; set; } = null!;
        public string Breed { get; set; } = null!;
        public int? GroupId { get; set; }
        public int? CustomerId { get; set; }
        public string BlobUrl { get; set; } = null!;

        public virtual Customer? Customer { get; set; }
        public virtual Group? Group { get; set; }
    }
}

DogDC/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogDC.Models;
using System.Security.Claims;

namespace DogDC.Controllers
{
    public class PetController : Controller
    {
        private readonly DogdcDBContext _context;

        public PetController(DogdcDBContext context)
        {
            _context = context;
        }

        //GET: Pet/Index/Customer
        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            var userId = user?.IsAdmin;
            ViewBag.UserIsAdmin = userId;

            var dogdcDBContext = _context.Pets
                .Include(p => p.Customer)
                .Include(p => p.Group)
                .Where(p => p.Customer.Email == userEmail)
                ;
            return View(await dogdcDBContext.ToListAsync());
        }

        // GET: Pet/Details/Customer
        public async Task<IActionResult> Details(int? id)
        {

            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (id == null || _context.Pets == null)
                {
                    return NotFound();
                }

                var pet = await _context.Pets
                    .Include(p => p.Customer)
                    .Include(p => p.Group)
                    .Where(p => p.Customer.Email == userEmail)
                    .FirstOrDefaultAsync(m => m.Id == id)
                    ;

                if (pet == null)
                {
                    return NotFound();
                }

                return View(pet);
           
        }

        // GET: Pet/Create/Customer&Admin
        public IActionResult Create()
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.CustomerId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Id");
            return View();
        }

        // POST: Pet/Create/Customer&Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Diet,Breed,GroupId,CustomerId,BlobUrl")] Pet pet)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.CustomerId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;
          
            if (ModelState.IsValid)
            {
                _context.Add(pet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", pet.CustomerId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Id", pet.GroupId);
            return View(pet);
        }

        // GET: Pet/Edit/Customer
        public async Task<IActionResult> Edit(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.CustomerId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .Include(p => p.Customer)
                .Include(p => p.Group)
                .Where(p => p.Customer.Email == userEmail)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (pet == null)
            {
                return NotFound();
            }
            //ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", pet.CustomerId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Id", pet.GroupId);
            return View(pet);
        }

        // POST: Pet/Edit/Customer&Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Diet,Breed,GroupId,CustomerId,BlobUrl")] Pet pet)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.CustomerId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;
            var admin = user?.IsAdmin;
            ViewBag.UserIsAdmin = admin;

            if (id != pet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", pet.CustomerId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Id", pet.GroupId);
            return View(pet);
        }

        // GET: Pet/Delete/Customer
        public async Task<IActionResult> Delete(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .Include(p => p.Customer)
                .Include(p => p.Group)
                .Where(p => p.Customer.Email == userEmail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        // POST: Pet/Delete/Customer&Admin
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pets == null)
            {
                return Problem("Entity set 'DogdcDBContext.Pets'  is null.");
            }
            var pet = await _context.Pets.FindAsync(id);
            if (pet != null)
            {
                _context.Pets.Remove(pet);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetExists(int id)
        {
          return (_context.Pets?.Any(e => e.Id == id)).GetValueOrDefault();
        }




        //-------------- TÄSTÄ ALKAA ADMIN OSASTO---------------
        //------------------------------------------------------
        //------------------------------------------------------


        //GET: Pet/Index/Admin
        [Authorize(Roles = "Administrator")]
        public ActionResult IndexAdmin(string sortOrder)
        {
            ViewBag.GroupSortParm = String.IsNullOrEmpty(sortOrder) ? "group_desc" : "";
            ViewBag.CustomerSortParm = String.IsNullOrEmpty(sortOrder) ? "cust_desc" : "";
            var dogs = from s in _context.Pets
                       .Include(p => p.Customer)
                       .Include(p => p.Group)
                       select s;
            switch (sortOrder)
            {
                case "group_desc":
                    dogs = dogs.OrderBy(s => s.GroupId);
                    break;
                case "cust_desc":
                    dogs = dogs.OrderBy(s => s.Customer.LastName);
                    break;
                default:
                    dogs = dogs.OrderBy(s => s.Name);
                    break;
            }
            return View("IndexAdmin", dogs.ToList());
        }

        // GET: Pet/Details/Admin
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DetailsAdmin(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            var userId = user?.IsAdmin;
            ViewBag.UserIsAdmin = userId;

            if (id == null || _context.Pets == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .Include(p => p.Customer)
                .Include(p => p.Group)
                .FirstOrDefaultAsync(m => m.Id == id)
                ;

            if (pet == null)
            {
                return NotFound();
            }

DogDC/Views/Pet/Create.cshtml
@model DogDC.Models.Pet

@{
    ViewData["Title"] = "Create";
}
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

        <ol>
            <br />
        </ol>
        <h2>Lisää uusi lemmikki</h2>

    </div>
</section><!-- End Breadcrumbs -->

<hr />
<!-- ======= Add Pet Section ======= -->
<section id="portfolio-details" class="portfolio-details">
    <div class="container">

        <div class="row gy-4">

            <div class="col-lg-8">
                <div class="portfolio-details-slider swiper">
                    <div class="swiper-wrapper align-items-center">

                        <div class="swiper-slide">
                            <img src="https://dogdc.blob.core.windows.net/dogdc/koirajaKeppiv.jpg" alt="">
                        </div>
                        <p>


                        </p>
                        <div class="swiper-slide">
                            <img src="https://dogdc.blob.core.windows.net/dogdc/koirajaPumpkinsv.jpg" alt="">
                        </div>

                    </div>
                    <div class="swiper-pagination"></div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="portfolio-info">
                    <h3>Täytä lemmikin tiedot</h3>
                    <ul>
                        <div class="row">
                            <div class="col-md-4">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label">Nimi</label>
                                        <input asp-for="Name" class="form-control" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Age" class="control-label">Ikä</label>
                                        <input asp-for="Age" class="form-control" />
                                        <span asp-validation-for="Age" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Diet" class="control-label">Ruokavalio</label>
                                        <input asp-for="Diet" class="form-control" />
                                        <span asp-validation-for="Diet" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Breed" class="control-label">Rotu</label>
                                        <input asp-for="Breed" class="form-control" />
                                        <span asp-validation-for="Breed" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="GroupId" class="control-label">Ryhmä</label>
                                        <select asp-for="GroupId" class="form-control">
                                            <option value="1">Pennut</option>
                                            <option value="2">Aikuiset</option>
                                            <option value="3">Seniorit</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <input type ="hidden" id="CustomerId" name="CustomerId" class="form-control" value="@ViewBag.CustomerId"></input>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="BlobUrl" class="control-label">Lemmikin kuva (url)</label>
                                        <input asp-for="BlobUrl" class="form-control" />
                                        <span asp-validation-for="BlobUrl" class="text-danger"></span>
                                    </div>
                                    <br />
                                    <div class="form-group">
                                        <input type="submit" value="Tallenna" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </ul>
                </div>
                <div class="portfolio-description">
                    <h2>Muista täyttää tiedot tarkasti</h2>
                    <p>
                        Huolellisesti täytetyt tiedot takaavat sen, että koirasi saa päiväkodissa juuri oikeaa hoitoa kuten esimerkiksi oman ruokavalionsa. Olettehan yhteydessä meihin, mikäli jokin kohta aiheuttaa teille haasteita.
                    </p>
                </div>
            </div>

        </div>

    </div>
</section><!-- End of the Add Pet Section -->
@*<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nimi</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label">Ikä</label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diet" class="control-label">Ruokavalio</label>
                <input asp-for="Diet" class="form-control" />
                <span asp-validation-for="Diet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label">Rotu</label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Ryhmän ID</label>
                <select asp-for="GroupId" class ="form-control" asp-items="ViewBag.GroupId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label">Omistajan ID</label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="BlobUrl" class="control-label">Lemmikin kuva (url)</label>
                <input asp-for="BlobUrl" class="form-control" />
                <span asp-validation-for="BlobUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Luo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Takaisin</a>
    <a class="btn btn-light" asp-controller="Pet" asp-action="IndexAdmin">Admin</a>
</div>*@

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

DogDC/Views/Pet/Delete.cshtml
@model DogDC.Models.Pet

@{
    ViewData["Title"] = "Delete";
}
 <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

            <ol>
                <li>Poista</li>
                <li>Lemmikki</li>
            </ol>
            <h2>Haluatko varmasti poistaa lemmikin?</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nimi
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Ikä
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            Ruokavalio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Diet)
        </dd>
        <dt class="col-sm-2">
            Rotu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Breed)
        </dd>
        <dt class="col-sm-2">
            Omistaja
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.FirstName)
            @Html.DisplayFor(model => model.Customer.LastName)
        </dd>
        <dt class="col-sm-2">
            Ryhmä
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group.Name)
        </dd>
        <dd class="col-sm-10">
            <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <img src="@(Model.BlobUrl !=null ? Model.BlobUrl :"https://mdbootstrap.com/img/new/standard/nature/184.jpg")" class="img-fluid" alt="...">
            </div>
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Poista" class="btn btn-danger" /> 
        @{
            if (ViewBag.UserIsAdmin == 1)
            {<a class="btn btn-light" asp-action="IndexAdmin">Takaisin</a>}
            else
            { <a class="btn btn-light" asp-action="Index">Takaisin</a>}
        }
       

    </form>
</div>

DogDC/Views/Pet/Details.cshtml
@model DogDC.Models.Pet

@{
    ViewData["Title"] = "Details";
}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

        <ol>
            <li>Lisätietoja</li>
            <li>Lemmikki</li>
        </ol>
        <h2>Lemmikin tiedot</h2>

    </div>
</section>
<!-- End Breadcrumbs -->

<hr />
<dl class="row">
    <dt class="col-sm-2">
        Nimi
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        Ikä
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Age)
    </dd>
    <dt class="col-sm-2">
        Ruokavalio
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Diet)
    </dd>
    <dt class="col-sm-2">
        Rotu
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Breed)
    </dd>
    <dt class="col-sm-2">
        Omistaja
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Customer.FirstName)
        @Html.DisplayFor(model => model.Customer.LastName)
    </dd>
    <dt class="col-sm-2">
        Ryhmä
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Group.Name)
    </dd>
    <dd class="col-sm-10">
        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
            <img src="@(Model.BlobUrl !=null ? Model.BlobUrl :"https://mdbootstrap.com/img/new/standard/nature/184.jpg")" class="img-fluid" alt="...">
        </div>
    </dd>
    <div>
    @{
        if (ViewBag.UserIsAdmin == 1)
        {
            <a class="btn btn-light" asp-action="EditAdmin" asp-route-id="@Model?.Id">Muokkaa</a>
            <a class="btn btn-light" asp-action="IndexAdmin">Takaisin</a>
        }
        else
        {
            <a class="btn btn-light" asp-action="Edit" asp-route-id="@Model?.Id">Muokkaa</a>
            <a class="btn btn-light" asp-action="Index">Takaisin</a>
        }
    }

</div>
</dl>

DogDC/Views/Pet/Edit.cshtml
@model DogDC.Models.Pet

@{
    ViewData["Title"] = "Edit";
}
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

        <ol>
            @*<li>Muokkaa</li>
            <li>Lemmikki</li>*@
        </ol>
        <h2>Muokkaa lemmikin tietoja</h2>

    </div>
</section><!-- End Breadcrumbs -->
@*<h4>Muokkaa lemmikin tietoja</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nimi</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label">Ikä</label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diet" class="control-label">Ruokavalio</label>
                <input asp-for="Diet" class="form-control" />
                <span asp-validation-for="Diet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Breed" class="control-label">Rotu</label>
                <input asp-for="Breed" class="form-control" />
                <span asp-validation-for="Breed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Ryhmä</label>
                <select asp-for="GroupId" class="form-control">
                    <option value="1">Pennut</option>
                    <option value="2">Aikuiset</option>
                    <option value="3">Seniorit</option>
                </select>
            </div>
            <div class="form-group">
                <input type="hidden" id="CustomerId" name="CustomerId" class="form-control" value="@ViewBag.CustomerId"></input>
            </div>
            <div class="form-group">
                <label asp-for="BlobUrl" class="control-label">Lemmikin kuva (url)</label>
                <input asp-for="BlobUrl" class="form-control" />
                <span asp-validation-for="BlobUrl" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Tallenna" class="btn btn-primary" />
            </div>
            <br />
            <div>
                @{
                    if (ViewBag.UserIsAdmin == 1)
                    {
                        <a class="btn btn-light" asp-action="IndexAdmin">Takaisin</a>
                    }
                    else
                    {
                        <a class="btn btn-light" asp-action="Index">Takaisin</a>
                    }
                }
            </div>
        </form>
    </div>
</div>
<div class="row">
        <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">
                  <img src="https://dogdc.blob.core.windows.net/dogdc/JackrusselPinkkiv.jpg" width="40" height="600"  alt="">
              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

DogDC/Views/Pet/Index.cshtml
@model IEnumerable<DogDC.Models.Pet>

@{
    ViewData["Title"] = "Index";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Portfolio Details - Multi Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

</head>
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

            <ol>
                <li>Omistajan sivut</li>
                <li>Lemmikki</li>
            </ol>
            <h2>Lemmikkisi tiedot</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <p>
        <a asp-action="Create">Lisää uusi lemmikki</a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Nimi
                </th>
                <th>
                    Kuva
                </th>
                <th>
                    @Html.ActionLink("Omistaja", "Index", new { sortOrder = ViewBag.CustomerSortParm })
                    @*Omistaja*@
                </th>
                <th>
                    @Html.ActionLink("Ryhmä", "Index", new { sortOrder = ViewBag.GroupSortParm })
                    @*Ryhmä*@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <div class="col-lg-4 col-md-6 portfolio-item filter-card">
                            <img src="@(item.BlobUrl !=null ? item.BlobUrl :"https://mdbootstrap.com/img/new/standard/nature/184.jpg")" class="img-fluid" alt="...">
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer.FirstName)
                        @Html.DisplayFor(modelItem => item.Customer.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Group.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item?.Id">Muokkaa</a>
                        <a asp-action="Details" asp-route-id="@item.Id">Tiedot</a>
                        <a asp-action="Delete" asp-route-id="@item.Id"> Poista </a>
                    </td>
                </tr>
            }

</main><!-- End #main -->
    </tbody>
</table>