DogDC/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogDC.Models;
using System.Security.Claims;

namespace DogDC.Controllers
{
    public class CalendarController : Controller
    {
        private readonly DogdcDBContext _context;

        public CalendarController(DogdcDBContext context)
        {
            _context = context;
        }


        //GET: Calendar/Index/Customer
        public async Task<IActionResult> Index()
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            //var dogdcDBContext = _context.Bookings.Include(b => b.Utility);
            var dogdcDBContext = _context.Bookings
             .Include(b => b.Utility)
             .Where(p => p.BookingStatuses.FirstOrDefault().CustomerId == userId);

            return View(await dogdcDBContext.ToListAsync());
        }

        // GET: Calendar/Calendar
        public ActionResult Calendar(int? vuosi, int? kuukausi)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.IsAdmin;
            ViewBag.UserIsAdmin = userId;

            ViewData["vuosi"] = vuosi.HasValue ? vuosi.Value : DateTime.Today.Year;
            ViewData["kuukausi"] = kuukausi.HasValue ? kuukausi.Value : DateTime.Today.Month;
            return View();
        }

        // GET: Calendar/Details/Customer
        public async Task<IActionResult> Details(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Utility)
                .Where(p => p.BookingStatuses.FirstOrDefault().CustomerId == userId)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Calendar/Create/Customer&Admin
        public IActionResult Create()
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userIsAdminCheck = user?.IsAdmin;
            ViewBag.UserIsAdmin = userIsAdminCheck;

            ViewData["UtilityId"] = new SelectList(_context.Utilities, "Id", "Id");
            //ViewData["UtilityId"] = new SelectList(_context.Utilities, "Name", "Id");
            return View();
        }

        // POST: Calendar/Create/Customer&Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StartTime,EndTime,UtilityId")] Booking booking)
        {

            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
            }
            {
                var bookingId = booking.Id;
                BookingStatus bs = new BookingStatus { CustomerId = userId, BookingId = booking.Id };
                _context.BookingStatuses.Add(bs);
                await _context.SaveChangesAsync();
            }
            ViewData["UtilityId"] = new SelectList(_context.Utilities, "Id", "Id", booking.UtilityId);

            return View(booking);
        }

        // GET: Calendar/Edit/Customer
        public async Task<IActionResult> Edit(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;

            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Where(p => p.BookingStatuses.FirstOrDefault().CustomerId == userId)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (booking == null)
            {
                return NotFound();
            }
            ViewData["UtilityId"] = new SelectList(_context.Utilities, "Id", "Id", booking.UtilityId);
            return View(booking);
        }

        // POST: Calendar/Edit/Customer&Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StartTime,EndTime,UtilityId")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
              
                return RedirectToAction(nameof(Index));
            }
            ViewData["UtilityId"] = new SelectList(_context.Utilities, "Id", "Id", booking.UtilityId);
            return View(booking);
        }

        // GET: Calendar/Delete/Customer
        public async Task<IActionResult> Delete(int? id)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.Id;
            ViewBag.userId = _context.Customers.FirstOrDefault(u => u.Email == userEmail)?.Id;
         
            var userIsAdminCheck = user?.IsAdmin;
            ViewBag.UserIsAdmin = userIsAdminCheck;

            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
               .Include(p => p.Utility)
               .Where(p => p.BookingStatuses.FirstOrDefault().CustomerId == userId)
               .FirstOrDefaultAsync(p => p.Id == id);

            var bookingstatus = await _context.BookingStatuses
                .Include(p => p.Booking)
                .Include(p => p.Customer)
                .FirstOrDefaultAsync(p => p.Booking.Id == id);


            if (booking == null)
            { 
             return NotFound();
            }

            return View(booking);
        }

        // POST: Calendar/Delete/Customer&Admin
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bookings == null && _context.BookingStatuses == null)
            {
                return Problem("Entity set 'DogdcDBContext.Bookings'  is null.");
            }
            var booking = await _context.Bookings.FindAsync(id);
            var bookingstatus = await _context.BookingStatuses
                .Include(p => p.Booking)
                .FirstOrDefaultAsync(p => p.Booking.Id == id);

            if (booking != null && bookingstatus != null)
            {
                _context.BookingStatuses.Remove(bookingstatus);
                _context.Bookings.Remove(booking);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
          return (_context.Bookings?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private bool BookingStatusExists(int id)
        {
            return (_context.BookingStatuses?.Any(e => e.Id == id)).GetValueOrDefault();
        }




        //-------------- TÄSTÄ ALKAA ADMIN OSASTO---------------
        //------------------------------------------------------
        //------------------------------------------------------


        // GET: Calendar/Index/Admin
        [Authorize(Roles = "Administrator")]
        public ActionResult IndexAdmin(string sortOrder)
        {
            var bookings = from b in _context.Bookings
                           .Include(b => b.Utility)
                           select b;
            switch (sortOrder)
            {
                case "group_desc":
                    bookings = bookings.OrderBy(s => s.EndTime);
                    break;
                case "cust_desc":
                    bookings = bookings.OrderBy(s => s.UtilityId);
                    break;
                default:
                    bookings = bookings.OrderBy(s => s.StartTime);
                    break;
            }
            return View("IndexAdmin", bookings.ToList());
        }

        // GET: Calendar/Details/Admin
        [Authorize(Roles = "Administrator")]

DogDC/Controllers/UtilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogDC.Models;
using System.Security.Claims;

namespace DogDC.Controllers
{
    public class UtilityController : Controller
    {
        private readonly DogdcDBContext _context;
        public UtilityController(DogdcDBContext context)
        {
            _context = context;
        }

        // GET: Utility
        public ActionResult Index(string searchString)
        {
            var userEmail = User.FindFirst(c => c.Type == ClaimTypes.Email)?.Value;
            var user = _context.Customers.FirstOrDefault(u => u.Email == userEmail);
            var userId = user?.IsAdmin;
            ViewBag.UserIsAdmin = userId;

            var utilities = from s in _context.Utilities.Include(p => p.Category)
                       select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                utilities = utilities.Where(s => s.Name.Contains(searchString)
                                       || s.Category.Name.Contains(searchString));
            }
            return View(utilities.ToList());
        }
        public async Task<IActionResult> GetUtilitiesByCategory(int id)
        {
            var utilities = _context.Utilities.Include(p => p.Category).Where(i => i.Category.Id == id);
            ViewBag.Header = utilities.First().Category.Name;
            return View("Index", await utilities.ToListAsync());
        }

        // GET: Utility/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Utilities == null)
            {
                return NotFound();
            }

            var utility = await _context.Utilities
                .Include(u => u.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utility == null)
            {
                return NotFound();
            }

            return View(utility);
        }

        // GET: Utility/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id");
            return View();
        }

        // POST: Utility/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,CategoryId")] Utility utility)
        {
            if (ModelState.IsValid)
            {
                _context.Add(utility);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", utility.CategoryId);
            return View(utility);
        }

        // GET: Utility/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            
            if (id == null || _context.Utilities == null)
            {
                return NotFound();
            }

            var utility = await _context.Utilities.FindAsync(id);
            if (utility == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", utility.CategoryId);
            return View(utility);
        }

        // POST: Utility/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,CategoryId")] Utility utility)
        {
            if (id != utility.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utility);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilityExists(utility.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", utility.CategoryId);
            return View(utility);
        }

        // GET: Utility/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Utilities == null)
            {
                return NotFound();
            }

            var utility = await _context.Utilities
                .Include(u => u.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utility == null)
            {
                return NotFound();
            }

            return View(utility);
        }

        // POST: Utility/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Utilities == null)
            {
                return Problem("Entity set 'DogdcDBContext.Utilities'  is null.");
            }
            var utility = await _context.Utilities.FindAsync(id);
            if (utility != null)
            {
                _context.Utilities.Remove(utility);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UtilityExists(int id)
        {
          return (_context.Utilities?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DogDC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="https://dogdc.blob.core.windows.net/dogdc/pawFavicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DogDC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DogDC.styles.css" asp-append-version="true" />

   
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Portfolio Details - Multi Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

</head>
<body>
   @* <header>*@
    <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a>Koirapäiväkoti</a></h1>


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @* <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Etusivu</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Etusivu</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Koirapaivakoti">Koirapäiväkoti</a>
                            </li>
                           @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                            @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Kirjaudu ulos</a>
                            </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Calendar">Kalenteri</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="UserProfile">Profiilisivu</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Palvelut</a>
                                <div class="dropdown-menu">
                                    @Html.ActionLink("Kaikki palvelut", "Index","Utility", null, new {@class="dropdown-item",})
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Retket", "GetUtilitiesByCategory","Utility",new { id=1 }, new {@class="dropdown-item",})
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Hoidot", "GetUtilitiesByCategory","Utility",new { id=2 }, new {@class="dropdown-item",})
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Aktiviteetit", "GetUtilitiesByCategory","Utility",new { id=3 }, new {@class="dropdown-item",})
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Teemapäivät", "GetUtilitiesByCategory","Utility",new { id=4 }, new {@class="dropdown-item",})
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Kuvaukset", "GetUtilitiesByCategory","Utility",new { id=5 }, new {@class="dropdown-item",})
                                </div>
                                
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Kirjaudu ulos</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Etusivu</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Koirapaivakoti">Koirapäiväkoti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Kirjaudu sisään</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>


        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DogDC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>